### ISSUE TITLE
Fix source code copy/source links

### ISSUE THREAD

**Issue by jrudolph** [apache/incubator-pekko-sbt-paradox#38]
It seems they are currently slightly messed up:

![image](https://user-images.githubusercontent.com/9868/222113819-0c23e682-d369-4b0e-a413-aeb727de2925.png)

from https://nightlies.apache.org/pekko/docs/pekko-http/main-snapshot/docs/introduction.html

**Comment by pjfanning** [comment]
I'm not arguing that this should not be fixed. The current setup basically works but it isn't perfect.
* You can copy to clipboard because an icon appears in top right of source pane
* You can click 'source' and that acts as a hyperlink to the source code
* So main issue is that the word 'copy' is prepended to 'source' - this is not part of the hyperlink - the 'copy' just appears as text
* If we could get rid of the word 'copy', things would be better
* there might be more elegant solutions

See https://pekko.apache.org/docs/pekko-http/current/introduction.html#streaming for an example

fyi @mdedetrich

**Comment by pjfanning** [comment]
This could also be more of a CSS problem. These 2 classes
* snippet-button
* copy-snippet

The HTML comes from sbt-paradox and it seems that if you apply the right CSS styling that the display looks correct - eg https://doc.akka.io/docs/akka-http/current/introduction.html#streaming

**Comment by jrudolph** [comment]
I started looking into that some months ago, and I agree it's an CSS artifact that I think comes from some unexpected combination of stylesheets in our particular case.

**Comment by pjfanning** [comment]
I was trying to copy some stuff from the CSS in sbt-paradox-akka into our CSS locally but I haven't found the right combination of changes yet. I need to get back to the release so will stop looking at this.
