### ISSUE TITLE
do we need cookie support?

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko-sbt-paradox#71]
https://lists.apache.org/thread/bh1vqjnf7vjzyzhgbcv979g0hl6dly0s has failed - all the issues except those related to groups.js are already resolved in the git repo.

The cookie support copied from mozilla samples are the issue. In the end of the day, for Apache Pekko, we may not care about tracking cookies.

wdyt @jrudolph @mdedetrich

**Comment by pjfanning** [comment]
So I looked more closely at groups.js and the cookie is tracking whether the user wants Scala or Java tabs. I'll close this.

**Comment by mdedetrich** [comment]
I was going to say that this suggestion is quite rash, I already responding to the mailing list that there should not be any license issues (it appears that the original concern was an honest mistake).

**Comment by pjfanning** [comment]
@mdedetrich we are still left with the messy 2010 date thing and the difficulty in knowing if it is CC0 or MIT licensed. MIT license needs a copyright identifying original author.

**Comment by mdedetrich** [comment]
Yup, I am making an issue on Mozilla about it. Lets see if they respond in a timely manner, if they don't then we can make a decision

**Comment by jrudolph** [comment]
No, let's do nothing about it. There is no code copied from the Mozilla documentation and noone claimed there would be.

**Comment by jrudolph** [comment]
> no one claimed there would be

I.e. the link in the code does not in any way claim that something has been copied, it is just a link.

**Comment by jrudolph** [comment]
The second function which links to an example also has no significant code copies.

**Comment by pjfanning** [comment]
Thanks @jrudolph - could you comment on the mail thread? We're sort of stuck with this - any code comment that has a link is being used to issue -1s to our release candidates.

Would it be ok if we changed the comments to with the Mozilla links to explicitly state that we did not copy any code from the Mozilla docs?

**Comment by jrudolph** [comment]
I did, but I also still think we should not make a release of this module unless something or someone forces us to...

The module is not for outside consumption, so the value we get out of creating a proper release seem diminishing compared to the crazy cost of having lots of people involved verifying artifacts that no one but us will use. The most likely outcome will be, that we will often not be able to use the latest release of the theme because we might need lots of little fixes that we detect when going through the different module documentations and we do not want to wait every time until a proper release can be made to apply those fixes.

If we want nicer version numbers, let's create named snapshot builds and use those.

**Comment by mdedetrich** [comment]
> Thanks @jrudolph - could you comment on the mail thread? We're sort of stuck with this - any code comment that has a link is being used to issue -1s to our release candidates.

He already did

> Would it be ok if we changed the comments to with the Mozilla links to explicitly state that we did not copy any code from the Mozilla docs?

Honestly if its known that the code was not copied (I probably verified this by checking the git history) then simply stating `See <MDN link> for reference` is very clear in stating that its not copied code, rather that a developer can follow the link to get more details.

If we still get -1's due to this then there are far bigger problems tbh

**Comment by pjfanning** [comment]
I agree that releasing this code is not urgent but it doesn't feel right to use snapshot jars either. 

If we get this issue sorted out, there should be no more objections to us having a 1.0.0 release.

This module will probably drop down the list because once Pekko 1.0.0 is released - hopefully tonight - Pekko HTTP and other user facing releases are more urgent.

**Comment by mdedetrich** [comment]
> If we get this issue sorted out, there should be no more objections to us having a 1.0.0 release.

Lets put it another way, there is nothing to sort out since the code is original (at most we can re-clarify the statement about the link to MDN as further documentation as mentioned before).

I am being adamant here because if we are being so meticioulslcy judicious  when it comes to referencing every single type of code origination (to the point where many would argue its excessive) the other end of bargain is that we also need to be 100% correct about it specifically when its needed and when its not (which is this case).

Otherwise it sets a completely non constructive environment for project code development/governance.
